apiVersion: v1
kind: Service
metadata:
  name: terraapp-service
spec:
  selector:
    app: terraapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # This creates an external IP for public access
